<?php
$headTitle = 'Manage categories';
$this->headTitle($headTitle);
?>
<?= $this->getFlashMessenger($this->flashMessenger()) ?>
<br>
<div><a href="<?= $this->url('admin/categories', ['action' => 'add']) ?>" class="btn btn-default">Add category</a></div>
<?php if (! $this->categories) : ?>
<h5>List is empty</h5>
<?php else : ?>
<br>
<div class="row">
    <div class="col-sm-12">
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <tr>
                    <th>Category name</th>
                    <th>Parent category</th>
                    <th>Actions</th>
                </tr>
                <?php foreach ($this->categories as $category) : ?>
                <tr>
                    <td><?= $this->escapeHtml($category->getName()) ?></td>
                    <td><?= $this->escapeHtml($this->getCategoryParentName($category->getParentId())) ?></td>
                    <td>
                        <a href="<?= $this->url('admin/categories', ['action' => 'edit', 'id' => (int)$category->getId()]) ?>">
                            Edit
                        </a>
                        &nbsp;&nbsp;|&nbsp;&nbsp;
                        <?php
                        $form = $this->form;
                        $form->setAttributes([
                        'action' => $this->url('admin/categories', ['action' => 'delete', 'id' => (int)$category->getId()]),
                        'class' => 'form-delete-button delete-category-admin',
                        ]);
                        $form->prepare();

                        echo $this->form()->openTag($form);
                        echo $this->formHidden($form->get('csrf'));
                        /* Here jquery script(j-confirm-action.js) did not work with name 'submit' */
                        echo $this->formSubmit($form->get('submit')->setValue('Delete')->setAttribute('name', 'send')->removeAttribute('class', 'btn btn-default'));
                        echo $this->form()->closeTag();
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
<?php endif; ?>
